### ISSUE TITLE
What about the performance of the listview with large number of items?

### ISSUE THREAD

**Issue by jaydeepw** [amulyakhare/TextDrawable#13]
Calling

TextDrawable drawable = TextDrawable.builder()
                .buildRect("A", Color.RED);

continuously in any AdapterView will exhaust the app out of memory.
How will this be handeled?

**Comment by amulyakhare** [comment]
According to my understanding, creating new `drawable` instances in the `AdapterView` will not result in the application going out-of-memory. Since `ListView` will recycle views, when the `setImageDrawable(drawable)` is called, it will clear the reference to the old drawable (which will eventually get garbage collected). Can you elaborate, why do you think the application memory will be exhausted?

**Comment by jaydeepw** [comment]
True. The app will not run out of memory but it will require the app to increase the frequency of GC calls.
So, I guess, we can say it is optimized for listview or RecyclerView.
