### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by saket** [amulyakhare/TextDrawable#7]
Hi, thanks so much for the library. I have a small request, related to the random colors. The current implementation uses a fixed set of colors. Could you please add an option so that we can use our own? 

Thank you. :)

**Comment by pasdam** [comment]
Since you already figured it out, this comment is just for future reference.
In an [Activity](https://developer.android.com/reference/android/app/Activity) or a [Fragment](https://developer.android.com/reference/android/app/Fragment) you can do this:
```java
int color = getResources().getColor(R.color.my_custom_color);
TextDrawable drawable = TextDrawable.builder().buildRound(firstLetter, color);
```
[Source](https://developer.android.com/reference/android/content/res/Resources).
